<option value="BIO">Biography (BIO)</option>
<option value="CF">Children Fiction (CF)</option>
<option value="CIR">Circulation (CIR)</option>
<option value="CUR">Curriculum (CUR)</option>
<option value="CNF">Children Non-Fiction (CNF)</option>
<option value="EASY">Easy book (EASY)</option>
<option value="FIC">Fiction (FIC)</option>
<option value="FIL">Filipiniana (FIL)</option>
<option value="FOLIO">FOLIO</option>
<option value="GC">General Circulation (GC)</option>
<option value="PAP">Paperback (PAP)</option>
<option value="PB">Picture book (PB)</option>
<option value="REF">Reference (REF)</option>
<option value="RES">Reserve (RES)</option>
<option value="RF">Reference/Filipiniana (RF)</option>
<option value="SP">Special collection (SP)</option>
<option value="TR">Teacher reference (TR)</option>
<option value="TRF">Teacher reference Filipiniana (TRF)</option>
<option value="TXT">Textbook (TXT)</option>